// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgV4s8MHNajQcvkQclWo2ltnMlXj7PsCY',
    appId: '1:524171464130:web:1e61b3d34b5e3de1099a5b',
    messagingSenderId: '524171464130',
    projectId: 'cse1-teamf2',
    authDomain: 'cse1-teamf2.firebaseapp.com',
    storageBucket: 'cse1-teamf2.firebasestorage.app',
    measurementId: 'G-HH9W0VZ4QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IugiwWnXBzoquRL5IMqq717jA9-ar6E',
    appId: '1:524171464130:android:c2a4881fa653984a099a5b',
    messagingSenderId: '524171464130',
    projectId: 'cse1-teamf2',
    storageBucket: 'cse1-teamf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwvPRP-CvA-V0ZsYc2swyRezXbg4vPPg',
    appId: '1:524171464130:ios:4dff8414f1a9a792099a5b',
    messagingSenderId: '524171464130',
    projectId: 'cse1-teamf2',
    storageBucket: 'cse1-teamf2.firebasestorage.app',
    androidClientId: '524171464130-jlrtjqdbg9k5e6k24rd8rjph9r04bhmg.apps.googleusercontent.com',
    iosClientId: '524171464130-g6rrbu1n29rdc626silj7uv51mvsqnm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUnivents2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlwvPRP-CvA-V0ZsYc2swyRezXbg4vPPg',
    appId: '1:524171464130:ios:4dff8414f1a9a792099a5b',
    messagingSenderId: '524171464130',
    projectId: 'cse1-teamf2',
    storageBucket: 'cse1-teamf2.firebasestorage.app',
    androidClientId: '524171464130-jlrtjqdbg9k5e6k24rd8rjph9r04bhmg.apps.googleusercontent.com',
    iosClientId: '524171464130-g6rrbu1n29rdc626silj7uv51mvsqnm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUnivents2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgV4s8MHNajQcvkQclWo2ltnMlXj7PsCY',
    appId: '1:524171464130:web:140c53e5ea14abb5099a5b',
    messagingSenderId: '524171464130',
    projectId: 'cse1-teamf2',
    authDomain: 'cse1-teamf2.firebaseapp.com',
    storageBucket: 'cse1-teamf2.firebasestorage.app',
    measurementId: 'G-0ND4X9LBC7',
  );
}
